name: alpa
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2023.08.22
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.3
  - openssl=1.1.1w
  - pip=23.2.1
  - python=3.8.13
  - readline=8.1.2
  - setuptools=68.0.0
  - sqlite=3.38.5
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - absl-py==2.0.0
    - aiohttp==3.8.5
    - aiosignal==1.3.1
    - alpa==0.2.3
    - async-timeout==4.0.3
    - attrs==23.1.0
    - certifi==2023.7.22
    - charset-normalizer==3.2.0
    - chex==0.1.5
    - click==8.0.4
    - contourpy==1.1.1
    - cupy-cuda113==10.6.0
    - cycler==0.11.0
    - datasets==2.14.5
    - dill==0.3.7
    - distlib==0.3.7
    - dm-tree==0.1.8
    - etils==1.3.0
    - fastrlock==0.8.2
    - filelock==3.12.4
    - flax==0.6.2
    - fonttools==4.42.1
    - frozenlist==1.4.0
    - fsspec==2023.6.0
    - grpcio==1.58.0
    - huggingface-hub==0.17.2
    - idna==3.4
    - importlib-metadata==6.8.0
    - importlib-resources==6.1.0
    - jax==0.3.22
    - jsonschema==4.19.1
    - jsonschema-specifications==2023.7.1
    - kiwisolver==1.4.5
    - llvmlite==0.41.0
    - markdown-it-py==3.0.0
    - matplotlib==3.7.3
    - mdurl==0.1.2
    - ml-dtypes==0.2.0
    - msgpack==1.0.6
    - multidict==6.0.4
    - multiprocess==0.70.15
    - numba==0.58.0
    - numpy==1.23.0
    - opt-einsum==3.3.0
    - optax==0.1.7
    - packaging==23.1
    - pandas==2.0.3
    - pillow==10.0.1
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.10.0
    - protobuf==4.24.3
    - pulp==2.7.0
    - pyarrow==13.0.0
    - pygments==2.16.1
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - ray==2.1.0
    - referencing==0.30.2
    - regex==2023.8.8
    - requests==2.31.0
    - rich==13.5.3
    - rpds-py==0.10.3
    - safetensors==0.3.3
    - scipy==1.10.1
    - six==1.16.0
    - tensorstore==0.1.44
    - tokenizers==0.13.3
    - toolz==0.12.0
    - tqdm==4.66.1
    - transformers==4.33.2
    - typing-extensions==4.8.0
    - tzdata==2023.3
    - urllib3==2.0.5
    - virtualenv==20.24.5
    - xxhash==3.3.0
    - yarl==1.9.2
    - zipp==3.17.0

